services:
  nginx:
    build:
      context: docker/development/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - php-fpm:ro
    volumes:
      - ./docker/development/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
      - mysql
    restart: always
  php-fpm:
    build:
      context: docker/development/php-fpm
    volumes:
      - ./:/var/www/html:rw
      - ./docker/development/php-fpm/:/usr/local/etc/php
    ports:
      - "9000:9000"
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    restart: always
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
#    command: sh -c "composer update --no-interaction"

  mysql:
    build:
      context: docker/development/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      TZ: "Europe/Moscow"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - ./docker/development/mysql/data:/var/lib/mysql
      - ./docker/development/mysql/mysql_db_config.sql:/docker-entrypoint-initdb.d/complex-app.sql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

